//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class devproxy_header_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal devproxy_header_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(devproxy_header_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~devproxy_header_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          protocommPINVOKE.delete_devproxy_header_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint SOF {
    set {
      protocommPINVOKE.devproxy_header_t_SOF_set(swigCPtr, value);
    } 
    get {
      uint ret = protocommPINVOKE.devproxy_header_t_SOF_get(swigCPtr);
      return ret;
    } 
  }

  public devproxy_opcode_t code {
    set {
      protocommPINVOKE.devproxy_header_t_code_set(swigCPtr, (int)value);
    } 
    get {
      devproxy_opcode_t ret = (devproxy_opcode_t)protocommPINVOKE.devproxy_header_t_code_get(swigCPtr);
      return ret;
    } 
  }

  public uint datalen {
    set {
      protocommPINVOKE.devproxy_header_t_datalen_set(swigCPtr, value);
    } 
    get {
      uint ret = protocommPINVOKE.devproxy_header_t_datalen_get(swigCPtr);
      return ret;
    } 
  }

  public devproxy_header_t() : this(protocommPINVOKE.new_devproxy_header_t(), true) {
  }

}
