//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum devproxy_opcode_t {
  PROXY_CMD_WRITE,
  PROXY_CMD_READ,
  PROXY_REP_DONE,
  PROXY_REP_NACK,
  PROXY_REP_ERR,
  PROXY_OPCODE_LAST,
  PROXY_INT_VALUE = (int) 0x7FFFFFFF
}
