//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum proto_iodev_devices_t {
  PROTO_DEV_EMULSLAVE,
  PROTO_DEV_SERIAL,
  PROTO_DEV_USBDEV,
  PROTO_DEV_LIBUSB,
  PROTO_DEV_PROXY,
  PROTO_DEV_STM32
}
