/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class protocomm {
  public static proto_hdle_t proto_create(SWIGTYPE_p_proto_Device_t iodevice) {
    global::System.IntPtr cPtr = protocommPINVOKE.proto_create(SWIGTYPE_p_proto_Device_t.getCPtr(iodevice));
    proto_hdle_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new proto_hdle_t(cPtr, false);
    if (protocommPINVOKE.SWIGPendingException.Pending) throw protocommPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void proto_init(proto_hdle_t _this, SWIGTYPE_p_proto_Device_t iodevice) {
    protocommPINVOKE.proto_init(proto_hdle_t.getCPtr(_this), SWIGTYPE_p_proto_Device_t.getCPtr(iodevice));
    if (protocommPINVOKE.SWIGPendingException.Pending) throw protocommPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void proto_destroy(proto_hdle_t _this) {
    protocommPINVOKE.proto_destroy(proto_hdle_t.getCPtr(_this));
  }

  public static int proto_open(proto_hdle_t _this, string szPath) {
    int ret = protocommPINVOKE.proto_open(proto_hdle_t.getCPtr(_this), szPath);
    return ret;
  }

  public static int proto_close(proto_hdle_t _this) {
    int ret = protocommPINVOKE.proto_close(proto_hdle_t.getCPtr(_this));
    return ret;
  }

  public static proto_Status_t proto_readFrame(proto_hdle_t _this, short tout_ms) {
    proto_Status_t ret = (proto_Status_t)protocommPINVOKE.proto_readFrame(proto_hdle_t.getCPtr(_this), tout_ms);
    return ret;
  }

  public static int proto_writeFrame(proto_hdle_t _this, proto_Command_t command, SWIGTYPE_p_unsigned_char args) {
    int ret = protocommPINVOKE.proto_writeFrame(proto_hdle_t.getCPtr(_this), (int)command, SWIGTYPE_p_unsigned_char.getCPtr(args));
    return ret;
  }

  public static byte proto_getArgsSize(proto_Command_t cmd) {
    byte ret = protocommPINVOKE.proto_getArgsSize((int)cmd);
    return ret;
  }

  public static void proto_setReceiver(proto_hdle_t _this, SWIGTYPE_p_f_p_void_enum_proto_Command_t_p_unsigned_char__int callback, SWIGTYPE_p_void userdata) {
    protocommPINVOKE.proto_setReceiver(proto_hdle_t.getCPtr(_this), SWIGTYPE_p_f_p_void_enum_proto_Command_t_p_unsigned_char__int.getCPtr(callback), SWIGTYPE_p_void.getCPtr(userdata));
  }

  public static int proto_pushToFrame(proto_hdle_t _this, SWIGTYPE_p_unsigned_char buf, uint len) {
    int ret = protocommPINVOKE.proto_pushToFrame(proto_hdle_t.getCPtr(_this), SWIGTYPE_p_unsigned_char.getCPtr(buf), len);
    return ret;
  }

  public static proto_DecodeStatus_t proto_decodeFrame(proto_hdle_t _this, SWIGTYPE_p_proto_Command_t cmd, proto_frame_data_t arg) {
    proto_DecodeStatus_t ret = (proto_DecodeStatus_t)protocommPINVOKE.proto_decodeFrame(proto_hdle_t.getCPtr(_this), SWIGTYPE_p_proto_Command_t.getCPtr(cmd), proto_frame_data_t.getCPtr(arg));
    return ret;
  }

  public static byte proto_makeFrame(proto_Frame_t frame, proto_Command_t command, SWIGTYPE_p_unsigned_char args) {
    byte ret = protocommPINVOKE.proto_makeFrame(proto_Frame_t.getCPtr(frame), (int)command, SWIGTYPE_p_unsigned_char.getCPtr(args));
    return ret;
  }

  public static readonly int proto_MAX_ARGS = protocommPINVOKE.proto_MAX_ARGS_get();
  public static readonly int proto_START_OF_FRAME = protocommPINVOKE.proto_START_OF_FRAME_get();
  public static readonly int proto_COMMAND_OFFSET = protocommPINVOKE.proto_COMMAND_OFFSET_get();
  public static readonly int proto_ARGS_OFFSET = protocommPINVOKE.proto_ARGS_OFFSET_get();
  public static readonly int proto_FRAME_MAXSIZE = protocommPINVOKE.proto_FRAME_MAXSIZE_get();

  public static readonly int PROTO_WAIT_FOREVER = protocommPINVOKE.PROTO_WAIT_FOREVER_get();
}
