/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum proto_Status_t {
  proto_NO_ERROR,
  proto_ERR_SYS,
  proto_ERR_CRC,
  proto_PEER_ERR_CRC,
  proto_INVALID_ARG,
  proto_TIMEOUT,
  proto_ERR_PROTO
}
