//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class proto_frame_data_req : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal proto_frame_data_req(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(proto_frame_data_req obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~proto_frame_data_req() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          protocommPINVOKE.delete_proto_frame_data_req(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public byte reg {
    set {
      protocommPINVOKE.proto_frame_data_req_reg_set(swigCPtr, value);
    } 
    get {
      byte ret = protocommPINVOKE.proto_frame_data_req_reg_get(swigCPtr);
      return ret;
    } 
  }

  public byte value {
    set {
      protocommPINVOKE.proto_frame_data_req_value_set(swigCPtr, value);
    } 
    get {
      byte ret = protocommPINVOKE.proto_frame_data_req_value_get(swigCPtr);
      return ret;
    } 
  }

  public proto_frame_data_req() : this(protocommPINVOKE.new_proto_frame_data_req(), true) {
  }

}
