/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum proto_Command_t {
  proto_CMD_SET,
  proto_CMD_GET,
  proto_CMD_REPLY,
  proto_CMD_ERR_CRC,
  proto_CMD_ERR_ARG,
  proto_LAST
}
